# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63fe1da951c55e48bce51b1e53882a86f938a0eb7b5a9753836009f09d93bc5f544b58c8b4f2defdea8c3bd2e0b21b8d03d568983769e0a2deef2cb827fb1712

test:
  secret_key_base: d14252cd01c12529a76834aace13dbe83148b46c413b4583dcac3491f65aa3dfabbff65f99e1b634b2dcce4cf2786a6c64c59952e1541116872d567ae214a5c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
